### ISSUE TITLE
npm run dev doesn't work well

### ISSUE THREAD

**Issue by fr-irene** [GoogleChromeLabs/sample-media-pwa#36]
Hi, I wanted to try running this project on my local computer, I did the npm install and added the config files,
But when I run the npm run dev, these error occurs.

`> googlechrome-biograf@12.1.5 build-resource-list /Users/01138260/Documents/GitHub/sample-media-pwa
> node build/build-resource-list.js

(node:9780) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
child_process.js:400
    throw new TypeError('"cwd" must be a string');
    ^

TypeError: "cwd" must be a string
    at normalizeSpawnArguments (child_process.js:400:11)
    at exports.spawn (child_process.js:493:38)
    at /Users/01138260/Documents/GitHub/sample-media-pwa/node_modules/parallelshell/index.js:104:17
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/01138260/Documents/GitHub/sample-media-pwa/node_modules/parallelshell/index.js:100:6)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! googlechrome-biograf@12.1.5 dev: `npm run build && parallelshell "npm run watch" "npm run serve"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the googlechrome-biograf@12.1.5 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/01138260/.npm/_logs/2018-01-24T04_43_37_764Z-debug.log`

Do you know why is it and how to fix this?

**Comment by storytellerr** [comment]
i am facing same issue. did you got the solution?

**Comment by Malaratgithub** [comment]
I also face same issue

**Comment by badersur** [comment]
Using node 7 instead of node 8 & 9 will solve the issue.

**Comment by ayudhDas** [comment]
Hi guys. Just replacing parallelshell worked for me in node v8.11.1
Please follow the pull request [ https://github.com/GoogleChromeLabs/sample-media-pwa/pull/38 ] to fix this. Or clone my fork of this repo [ https://github.com/ayudhDas/sample-media-pwa ]

A big shout out to @paullewis for the developer diaries for this repo.

**Comment by JoseVivanco2** [comment]
@ayudhDas I tried your fix but now I'm getting something else. This did happen to you as well?

`(node:3488) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
sh: concurrently: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! googlechrome-biograf@12.1.6 dev: `npm run build && concurrently "npm run watch" "npm run serve"`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the googlechrome-biograf@12.1.6 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`
